# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'

# for PowerShell Core
steps:
- pwsh: (Get-Content https://github.com/Den-kovalevskiy/PS/blob/e001be8caca79add2afd450cc0ff707f545fa6e9/Connection.txt) -replace '__TOKEN__', 'SQL-srv-01'


