# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: windows-latest

steps:
- task: ReplaceInFilesBetweenText@2
  inputs:
    parameterSearchDirectory: '$(Build.SourcesDirectory)'
    parameterSearchStart: '__TOKEN__'
    parameterSearchEnd: '__TOKEN__'
    parameterReplaceText: 'SQL-srv-01'
    parameterTypeOfSearch: 'filesSearchPattern'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'



