# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: windows-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

  

- task: ReplaceInFilesBetweenText@2
  inputs:
    parameterSearchDirectory: '$(Build.SourcesDirectory)'
    parameterSearchStart: '__TOKEN__'
    parameterSearchEnd: '__TOKEN__'
    parameterReplaceText: 'SQL-srv-01'
    parameterTypeOfSearch: 'filesSearchPattern'
    

- script:
- task: CopyFiles@2
  inputs:
    Contents: '**/*.txt'
    TargetFolder: '$(build.artifactstagingdirectory)'